### ISSUE TITLE
Evento: Xamarin dev days (Argentina)

### ISSUE THREAD

**Issue by nmilcoff** [standuplatam/temas#1]
## Xamarin dev days en Argentina (Rosario)

https://ti.to/xamarin/dev-days-argentina
#### \* Descripción del tema / publicación

Desde Rosario estamos organizando una Xamarin Dev Days para el 22 de octubre, si bien no está relacionado 100% con .Net Core, si con la plataforma .Net. Agradeceríamos mucho si pueden nombrarlo para los que aún no se enteraron ;)
#### \* Algo sobre vos (ej.: nombre, twitter handle, etc.)

Organizadores:

[https://twitter.com/nicomilcoff](url)
[https://twitter.com/fede_macca](url)
#### \* En caso de ser un tema ¿Por qué queres que lo tratemos?

Nos gustaría que nadie se lo pierda!
#### \* País

Argentina

**Comment by ealsur** [comment]
Agendado para el proximo standup! Gracias!
